<?php
/**
 * Implements hook_custom_theme().
 *
 * This function determines which theme the site will use based on which URL is
 * used to access the site, the default URL or the mobile (m.) URL. Viewport
 * detection and redirection is performed by the rover.js script added to the
 * head of each page.
 *
 * @global string $theme
 * @global string $base_url
 * @return string
 */
function rover_custom_theme() {
  global $theme;
  global $base_url;

  // Strip "www." from URL if it exists
  $default_url = str_replace('://www.', '://', $base_url);
  // Does URL contain "m." ? Set variable.
  $go_mobile = preg_match('/:\/\/m\./', $base_url) ? 1 : 0;
  // Pass variable to DOM
  drupal_add_js('jQuery.extend(Drupal.settings, { "destination_is_mobile": "' . $go_mobile . '" });', 'inline');

  if ($go_mobile == 1) {
    $mobile_url = $base_url;
    $default_url = str_replace('://m.', '://', $base_url);

    return 'mobile';
  }
  else {
    $mobile_url = str_replace('://', '://m.', $default_url);

    return $theme;
  }
  // Pass vars to DOM
  drupal_add_js('jQuery.extend(Drupal.settings, { "site_url": "' . $default_url . '" });', 'inline');
  drupal_add_js('jQuery.extend(Drupal.settings, { "mobile_url": "' . $mobile_url . '" });', 'inline');
  drupal_add_js(drupal_get_path('module', 'rover') . '/js/rover.js');
}

/**
 * Implements hook_menu().
 */
function rover_menu() {
  $items = array();

  $items['admin/config/user-interface/rover'] = array(
    'title' => 'ROVER: Mobile URL Detection',
    'description' => 'Enable theme switching for mobile devices.',
    //'position' => 'right',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rover_admin_settings_form'),
    'access arguments' => array('administer rover'),
    //'file' => 'rover.admin.inc',
    //'weight' => -15,
    'type' => MENU_NORMAL_ITEM
  );

  return $items;
}

/**
 * Implements hook_admin_settings_form().
 */
function rover_admin_settings_form($form, &$form_state) {

  $list_themes = list_themes($refresh = FALSE);
  $themes = array();

  foreach($list_themes as $theme) {
    if ($theme->status == 1) {
      $themes[] = $theme->name;
    }
  }

  $form['rover_admin_settings']['mobile_theme_screen_width'] = array(
    '#title' => 'Screen width',
    '#description' => 'Minimum screen width of a device browsing the site
      in pixels. When devices with smaller screens are detected, they are
      redirected to the m-dot URL (m.yourdomain.com).',
    '#type' => 'textfield',
    '#default_value' => variable_get('mobile_theme_screen_width'),
    '#size' => 5,
    '#maxlength' => 5,
    '#required' => TRUE
  );

  //  $themes = array('mobile', 'not mobile');
  $form['rover_admin_settings']['mobile_theme'] = array(
    '#title' => 'mobile theme',
    '#description' => 'Mobile theme to use when m. redirection is applied',
    '#type' => 'select',
    '#options' => $themes,
    '#default_value' => variable_get('mobile_theme'),
    '#required' => TRUE
  );

  return system_settings_form($form);
}

/**
 * Implements hook_permission().
 */
function rover_permission() {
  return array(
    'administer rover' => array(
      'title' => t('Configure theme switching for mobile.'),
      'description' => t('Set screen.width.'),
    ),
  );
}
